# Generated by Django 5.2.12 on 2026-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="The phone number being verified.",
                        max_length=15,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Base32 secret key for TOTP generation.",
                        max_length=32,
                        verbose_name="TOTP secret",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this verification was initiated.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether verification was successful.",
                        verbose_name="verified",
                    ),
                ),
            ],
            options={
                "verbose_name": "phone verification",
                "verbose_name_plural": "phone verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "verified"], name="phone_verify_idx"
                    )
                ],
            },
        ),
    ]
