# Generated by Django 5.2.12 on 2026-05-07 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_phoneverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The email being verified.",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA256 hash of the plaintext verification code.",
                        max_length=64,
                        verbose_name="code hash",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this verification code was generated.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this code has already been used.",
                        verbose_name="is used",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user verifying their email.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "email verification",
                "verbose_name_plural": "email verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email", "is_used"], name="email_verify_idx"),
                    models.Index(
                        fields=["user", "is_used"], name="user_email_verify_idx"
                    ),
                ],
            },
        ),
    ]
