# Generated by Django 5.2.12 on 2026-05-07 18:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneverification",
            name="session_token",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Unique token to identify this verification session.",
                max_length=64,
                unique=True,
                verbose_name="session token",
            ),
        ),
        migrations.AlterField(
            model_name="phoneverification",
            name="phone_number",
            field=models.CharField(
                help_text="The phone number being verified.",
                max_length=11,
                verbose_name="phone number",
            ),
        ),
        migrations.AddIndex(
            model_name="phoneverification",
            index=models.Index(fields=["session_token"], name="session_token_idx"),
        ),
    ]
