# Generated by Django 5.2.12 on 2026-05-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_phoneverification_session_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional full name of the user.",
                max_length=150,
                null=True,
                verbose_name="full name",
            ),
        ),
    ]
