version: '3.8'

services:
  web:
    build: .
    container_name: todo_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: >
      sh -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "

  redis:
    image: redis:7-alpine
    container_name: todo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  static_volume:
  media_volume:
  redis_data:
