# Generated by Django 5.2.12 on 2026-04-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_task_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"]},
        ),
    ]
